### ISSUE TITLE
18.9.26.(1:4).1 - Type is string

### ISSUE THREAD

**Issue by Pfenris** [ansible-lockdown/Windows-2019-CIS#55]
```
  win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\EventLog\Application
      name: Retention
      data: 0
      type: string
```

Should be
```
  win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windows\EventLog\Application
      name: Retention
      data: 0
      type: dword
```
_Retention | This value is of type REG_DWORD. The default value is 0._

ref: https://docs.microsoft.com/en-us/windows/win32/eventlog/eventlog-key
