### ISSUE TITLE
win2019cis_is_standalone is not defined

### ISSUE THREAD

**Issue by murrahjm** [ansible-lockdown/Windows-2019-CIS#63]
**Describe the Issue**
Task 2.3.6.1 fails on a domain joined server with the error that win2019cis_is_standalone is not defined. This variable is checked in the `when` clause for the task

Checking the prelim.yml file, the variable is set to true for workgroup machines, but does not appear to be set to false anywhere.

**Expected Behavior**
The task should process correctly for a domain joined machine

**Actual Behavior**
The conditional [      - not win2019cis_is_standalone](https://github.com/ansible-lockdown/Windows-2019-CIS/blob/main/tasks/section02.yml#L961) fails with a `not defined` error message.

This variable is set [in the prelim tasks](https://github.com/ansible-lockdown/Windows-2019-CIS/blob/1f15792c2b9fd3ff600b52dcdaf5c2f7b2b6228a/tasks/prelim.yml#L7) but only for a stand-alone server.  

This either needs to be set to false for a domain-joined machine, set to false in a defaults file, or set to false elsewhere, or the task needs to have a default value in the conditional.

**Control(s) Affected**
2019 playbook will not run to completion on a domain joined machine

**Environment (please complete the following information):**
 - git branch: [e.g main]
 - Ansible Version: [e.g. 2.12] 
 - Host Python Version: [e.g. Python 3.8]
 - Ansible Server Python Version: [e.g. Python 3.8]
 - Additional Details:

**Additional Notes**
Anything additional goes here

**Possible Solution**
```

      - name: set fact if domain member server
        set_fact:
            win2019cis_is_domain_member: true
            win2019cis_is_standalone: false
        when:
            - ansible_windows_domain_role == 'Member server'
```
